export const SET_SHOW_EDIT_GROCERY = 'SET_SHOW_EDIT_GROCERY';
export const SET_PURCHASE_STATUS = 'SET_PURCHASE_STATUS';
export const EDIT_GROCERY_SUCCESS = 'EDIT_GROCERY_SUCCESS';
export const DELETE_GROCERY_SUCCESS = 'DELETE_GROCERY_SUCCESS';
export const CHG_ADD_GROCERY_MODAL_STATE = 'CHG_ADD_GROCERY_MODAL_STATE';
export const ADD_GROCERY_SUCCESS = 'ADD_GROCERY_SUCCESS';
